import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Duane Johnson's 90th Birthday!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Happy Birthday Duane!
        </h1>


        
      </main>

      <footer>
       
          Powered by love
          
      </footer>
    </div>
  )
}
