import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Duane Johnson's 90th Birthday!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>
      <main>
        
        
       


        
      </main>

      <footer> 
        <Footer />
      </footer>
    </div>
  )
}
